id: P6B491A2F
initial_creation_type: ocr
source_metadata:
  volumes:
    37661271dac04f07972c2e0c07ec23b4:
      base_file: v083.txt
      image_group_id: I1PD95928
      title: འཕགས་པ་ཆོས་ཀྱི་དབྱིངས་ཀྱི་སྙིང་པོའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1296
      volume_number: 83
